apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: flask-dockerfile-example
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mdsaud-tenant/my-test-app/flask-dockerfile-example@sha256:290bc995b73c3df3c63b5077604b007f7df150abc9743fcc7a72b3410caa9c26
        name: container-image
        resources: {}
status: {}
