apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mdsaud-tenant/my-test-app/devfile-sample-code-with-quarkus@sha256:fecfc3d7ab4faf21a99f26b31b4b3b1f183ae00650cf88fea59e7373b9467abb
        name: my-java-quarkus
        resources: {}
status: {}
